#! /bin/sh

sxhkd &

bspc config top_padding 14 
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Steam follow=off desktop=II
bspc rule -a Spotify desktop=II
bspc rule -a "Battle.net" floating=true center=true desktop=III

~/.fehbg &
~/.config/bspwm/panel/panel &
